import type { Metadata } from 'next'
import './globals.css'
import { RedHat } from '@/Fonts/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
        <body className={`dark:bg-dark dark:text-white bg-white text-dark ${RedHat.className}`}>{children}</body>
    </html>
  )
}
